<?php
/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */

echo $block->sayHello();
// echo $block->helper();
 echo "<br/>";
// echo $block->sayHello1();
 echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner')->toHtml();
 echo $block->getUrl(); //to print the current path                   
 $url =  $block->getUrl('hellomagento/Index/Test', ['name' => 'Annie']);
 echo '<br/>';
 echo "<a href='$url'>view</a>";
 ?>
    