<h1>Details</h1>
<form action="<?php echo $block->getSaveAction() ?>" method="post">
   NAME: <input name="name" type="text" required/>
    AGE: <input name="age" type="number" required/>
    <input type="submit" value="Submit">
    
</form>
        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Age</th>
                <th>Delete</th>
                <th>Update</th>
            </tr>
            </thead>
            <tbody>
    <?php 
       
    $collection = $block->getTableData();
      foreach ($collection as $item): ?>  
      <tr>
        <td><?php
         echo $item->getId();
         ?></td>
        <td><?php echo $item->getName();?></td>
        <td><?php echo $item->getAge();?></td>
        <td><a href="<?php echo $this->getUrl('crudfrontend/index/delete', ['id' => $item->getId()]);?>">Delete</a></td>
        <td><a href="<?php echo $this->getUrl('crudfrontend/index/update', ['id' => $item->getId()]);?>">Update</a></td>
      </tr>
    <?php endforeach; ?></table>