<h1>Conversion Bug FAQ</h1>
<div data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
    <div data-role="collapsible">
        <div data-role="trigger">
            <div class="card">
                <div class="card-header" role="tab" id="headingOne">
                    <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-parent="#accordion" data-core="" href="#collapse1_473" aria-expanded="false" aria-controls="collapse1">
                        <h4 class="mbr-fonts-style display-5">
                            <span class="sign mbr-iconfont mbri-arrow-down inactive"></span> What is Magento?
                        </h4>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div data-role="content">
        <div id="collapse1_473" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body p-4">
                <p class="mbr-fonts-style panel-text display-7">
                Magento is an ecommerce platform that enables companies to run and manage their ecommerce sites in an optimized way. Magento functions as an open source ecommerce management system. It was first published by a Varien Inc in 2008, before being sold to eBay and ultimately spun off into its own entity. The 2.0 version of Magento arrived in November of 2015 and has improved the platform across the board.
            </div>
        </div>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">
            <div class="card-header" role="tab" id="headingTwo">
                <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-parent="#accordion" data-core="" href="#collapse2_473" aria-expanded="false" aria-controls="collapse2">
                    <h4 class="mbr-fonts-style display-5">
                        <span class="sign mbr-iconfont mbri-arrow-down inactive"></span> Why is Magento valuable for businesses?
                    </h4>
                </a>
            </div>
        </div>
    </div>
    <div data-role="content">
        <div id="collapse2_473" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingTwo">
            <div class="panel-body p-4">
                <p class="mbr-fonts-style panel-text display-7">
                Magento is valuable for businesses because it gives them a high level of control and flexibility when they are managing the look, functionality, and content of their ecommerce store. The Magento software is both extremely convenient, and extremely effective for running an ecommerce operation.
            </div>
        </div>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">
            <div class="card-header" role="tab" id="headingTwo">
                <a role="button" class="collapsed panel-title text-black" data-toggle="collapse" data-parent="#accordion" data-core="" href="#collapse2_473" aria-expanded="false" aria-controls="collapse2">
                    <h4 class="mbr-fonts-style display-5">
                        <span class="sign mbr-iconfont mbri-arrow-down inactive"></span> What are the different versions of Magento?
                    </h4>
                </a>
            </div>
        </div>
    </div>
    <div data-role="content">
        <div id="collapse2_473" class="panel-collapse noScroll collapse" role="tabpanel" aria-labelledby="headingTwo">
            <div class="panel-body p-4">
                <p class="mbr-fonts-style panel-text display-7">
                    Magento categorizes their product across multiple offerings:
                        <ul>
                            <li>Magento Commerce</li>
                            <li>Magento Order Management</li>
                            <li>Magento Business Intelligence</li>
                            <li>Magento Shipping</li>
                            <li>Magento Social</li>
                            <li>Magento Open Source</li>
                        </ul>
                </div>
            </div>
        </div>
    </div>
</div>

